timeout: 5

/HotaruOS
    protocol: limine

    # This is not kernel, this is just a loader.
    # Main kernel will be passed as module.
    kernel_path: boot():/arch-loader

    # This is our main kernel.
    # The kernel is gonna find the modules itself.
    module_path: boot():/hotaru-x86_64